service: study-chrgar-core-api-nodejs
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'eu-west-3'}
  stage: ${opt:stage, "dev"}
  profile: ${self:custom.profiles.${sls:stage}, 'asys-si-dev-serverless'}
  memorySize: 128
  timeout: 120
  environment:
    STUDY_TABLE: study_dynamodb_${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.STUDY_TABLE}"

functions:
  api:
    handler: crud/index.handler
    events:
      - httpApi:
          path: /up
          method: get
  add:
    handler: crud/add.handler
    events:
      - httpApi:
          path: /add
          method: post
  upd:
    handler: crud/upd.handler
    events:
      - http:
          path: /upd
          method: post
          private: true

plugins:
  - serverless-prune-versions
  - serverless-offline
  - serverless-dynamodb
  - serverless-plugin-typescript
  - serverless-dynamodb-local

custom:
  serverless-dynamodb:
    port: 8000
    stages:
      - local-dev
    start:
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  prune:
    automatic: true
    includeLayers: true
    number: 3

resources:
  Resources:
    OrganizationDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.STUDY_TABLE}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
